"""Standardized validation rules, severity classifications, and status enums."""

from enum import Enum


class ValidationSeverity(str, Enum):
    """Severity classification for validation check outcomes."""

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ValidationStatus(str, Enum):
    """Outcome status for individual rules or aggregate validation reports."""

    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


class ValidationRuleId(str, Enum):
    """Canonical registry of validation rule identifiers across all layers."""

    # Schema & Types
    SCHEMA_REQUIRED_COLUMNS = "SCHEMA_REQUIRED_COLUMNS"
    SCHEMA_DATA_TYPES = "SCHEMA_DATA_TYPES"
    SCHEMA_SYMBOL_VALID = "SCHEMA_SYMBOL_VALID"

    # Data Quality & OHLCV Integrity
    DATA_MISSING_VALUES = "DATA_MISSING_VALUES"
    DATA_OHLCV_INTEGRITY = "DATA_OHLCV_INTEGRITY"
    DATA_TIMESTAMP_VALID = "DATA_TIMESTAMP_VALID"
    DATA_CHRONOLOGICAL_ORDER = "DATA_CHRONOLOGICAL_ORDER"
    DATA_DUPLICATE_CANDLES = "DATA_DUPLICATE_CANDLES"
    DATA_TIMEFRAME_CONSISTENCY = "DATA_TIMEFRAME_CONSISTENCY"
    DATA_SUSPICIOUS_GAPS = "DATA_SUSPICIOUS_GAPS"
    DATA_PRICE_ANOMALIES = "DATA_PRICE_ANOMALIES"
    DATA_VOLUME_ANOMALIES = "DATA_VOLUME_ANOMALIES"

    # Feature Quality
    FEATURE_SCHEMA = "FEATURE_SCHEMA"
    FEATURE_MISSING_VALUES = "FEATURE_MISSING_VALUES"
    FEATURE_INFINITE_VALUES = "FEATURE_INFINITE_VALUES"
    FEATURE_TIMESTAMP_ALIGNMENT = "FEATURE_TIMESTAMP_ALIGNMENT"

    # Leakage Prevention
    LEAKAGE_LOOKAHEAD = "LEAKAGE_LOOKAHEAD"
    LEAKAGE_TARGET_IN_FEATURES = "LEAKAGE_TARGET_IN_FEATURES"
    LEAKAGE_TRAIN_TEST_OVERLAP = "LEAKAGE_TRAIN_TEST_OVERLAP"
    LEAKAGE_SCALER_PREPROCESSING = "LEAKAGE_SCALER_PREPROCESSING"

    # Model & Compatibility
    MODEL_EXISTENCE = "MODEL_EXISTENCE"
    MODEL_ARTIFACT_READABLE = "MODEL_ARTIFACT_READABLE"
    MODEL_FINGERPRINT_MATCH = "MODEL_FINGERPRINT_MATCH"
    MODEL_FEATURE_COMPATIBILITY = "MODEL_FEATURE_COMPATIBILITY"
    MODEL_INPUT_CONTRACT = "MODEL_INPUT_CONTRACT"
    MODEL_OUTPUT_CONTRACT = "MODEL_OUTPUT_CONTRACT"
