"""Domain models and data contracts for strategy decisions and trading signals."""

import uuid
from datetime import datetime, timezone
from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, field_validator

from adaptive_trading.domain.prediction import Prediction
from adaptive_trading.ml.validation.results import OOSPrediction


class SignalAction(StrEnum):
    """Action recommendation generated by a trading strategy."""

    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"


class StrategyPrediction(BaseModel):
    """Standardized prediction input contract consumed by the strategy engine."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    timestamp: datetime = Field(description="Timezone-aware observation timestamp")
    symbol: str = Field(min_length=1, description="Asset ticker symbol")
    predicted_class: str | int = Field(
        default="", description="Optional discrete predicted class"
    )
    probability_up: float = Field(
        ge=0.0,
        le=1.0,
        description="Predicted probability for upward movement in [0.0, 1.0]",
    )
    model_name: str = Field(
        default="", description="Name of model generating prediction"
    )
    model_version: str = Field(default="", description="Version identifier of model")

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("StrategyPrediction timestamp must be timezone-aware")
        return v

    @classmethod
    def from_prediction(cls, pred: Prediction, model_name: str = "") -> Self:
        """Convert a core domain Prediction object into a StrategyPrediction."""
        return cls(
            timestamp=pred.timestamp,
            symbol=pred.symbol,
            predicted_class="UP" if pred.probability_up >= 0.5 else "DOWN",
            probability_up=pred.probability_up,
            model_name=model_name,
            model_version=pred.model_version,
        )

    @classmethod
    def from_oos_prediction(
        cls,
        oos: OOSPrediction,
        model_name: str = "logistic_regression",
        model_version: str = "v1",
    ) -> Self:
        """Convert a Walk-Forward OOSPrediction record into a StrategyPrediction."""
        ts = oos.timestamp
        if ts is not None and (ts.tzinfo is None or ts.tzinfo.utcoffset(ts) is None):
            ts = ts.replace(tzinfo=timezone.utc)
        elif ts is None:
            ts = datetime.now(timezone.utc)

        return cls(
            timestamp=ts,
            symbol=oos.symbol or "UNKNOWN",
            predicted_class=oos.predicted_label,
            probability_up=oos.probability_up,
            model_name=model_name,
            model_version=model_version,
        )


class TradingSignal(BaseModel):
    """Structured trading signal generated by a Strategy."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    signal_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Unique identifier for the signal",
    )
    timestamp: datetime = Field(
        description="Timezone-aware timestamp when signal was evaluated"
    )
    symbol: str = Field(min_length=1, description="Asset ticker symbol")
    action: SignalAction = Field(description="Action decision (LONG/SHORT/NO_TRADE)")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Signal decision confidence score in [0.0, 1.0]",
    )
    strategy_name: str = Field(min_length=1, description="Name of generating strategy")
    strategy_version: str = Field(
        min_length=1, description="Version of generating strategy"
    )
    reason: str = Field(
        min_length=1, description="Human-readable rationale for the signal"
    )
    model_name: str = Field(
        default="", description="Name of the underlying prediction model"
    )
    model_version: str = Field(
        default="", description="Version of the underlying prediction model"
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("TradingSignal timestamp must be timezone-aware")
        return v


class SignalStatistics(BaseModel):
    """Diagnostic statistical summary of generated trading signals."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    total_predictions: int
    long_signals: int
    short_signals: int
    no_trade_signals: int
    long_percentage: float
    short_percentage: float
    no_trade_percentage: float
