"""Trading signals, risk decisions, orders, and execution fill domain models."""

from datetime import datetime
from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class SignalDirection(StrEnum):
    """Direction of a trading strategy signal."""

    BUY = "BUY"
    SELL = "SELL"
    FLAT = "FLAT"


class OrderSide(StrEnum):
    """Side of an order or trade."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    """Type of an order."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class Signal(BaseModel):
    """Trading signal generated by a strategy engine."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    signal_id: str = Field(min_length=1, description="Unique identifier for the signal")
    timestamp: datetime = Field(
        description="Timezone-aware timestamp when signal was produced"
    )
    symbol: str = Field(min_length=1, description="Market ticker symbol")
    direction: SignalDirection = Field(description="Signal direction (BUY/SELL/FLAT)")
    quantity: float = Field(ge=0, description="Recommended order quantity")
    entry_price: float | None = Field(
        default=None, gt=0, description="Target entry price"
    )
    stop_loss: float | None = Field(default=None, gt=0, description="Stop loss price")
    take_profit: float | None = Field(
        default=None, gt=0, description="Take profit price"
    )
    prediction_reference: str | None = Field(
        default=None,
        min_length=1,
        description="Optional identifier of source prediction",
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("Signal timestamp must be timezone-aware")
        return v

    @model_validator(mode="after")
    def validate_quantity_for_action(self) -> Self:
        """Ensure non-zero quantity for BUY or SELL signals."""
        if (
            self.direction in (SignalDirection.BUY, SignalDirection.SELL)
            and self.quantity <= 0
        ):
            raise ValueError(f"Quantity must be positive for {self.direction} signal")
        return self


class RiskDecision(BaseModel):
    """Evaluation result produced by the risk management engine."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    timestamp: datetime = Field(
        description="Timezone-aware timestamp when risk check was evaluated"
    )
    signal_id: str = Field(
        min_length=1, description="Identifier of the evaluated signal"
    )
    approved: bool = Field(description="True if signal passed all risk limits")
    reason: str | None = Field(
        default=None, description="Explanation if rejected or modified"
    )
    risk_limit_version: str = Field(
        min_length=1, description="Version tag of active risk limits"
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("RiskDecision timestamp must be timezone-aware")
        return v


class Order(BaseModel):
    """Order request submitted to an execution handler or broker adapter."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    order_id: str = Field(min_length=1, description="Unique identifier for the order")
    timestamp: datetime = Field(
        description="Timezone-aware timestamp when order was created"
    )
    symbol: str = Field(min_length=1, description="Market ticker symbol")
    side: OrderSide = Field(description="Order side (BUY/SELL)")
    quantity: float = Field(gt=0, description="Order quantity")
    order_type: OrderType = Field(description="Order execution type (MARKET/LIMIT)")
    price: float | None = Field(
        default=None, gt=0, description="Limit price if LIMIT order"
    )
    signal_id: str | None = Field(
        default=None,
        min_length=1,
        description="Optional identifier of triggering signal",
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("Order timestamp must be timezone-aware")
        return v

    @model_validator(mode="after")
    def validate_limit_order_price(self) -> Self:
        """Ensure LIMIT orders have a specified price."""
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("Price is required for LIMIT orders")
        return self


class Fill(BaseModel):
    """Execution fill confirmation produced by execution/simulation."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    fill_id: str = Field(min_length=1, description="Unique identifier for the fill")
    order_id: str = Field(min_length=1, description="Identifier of the filled order")
    timestamp: datetime = Field(
        description="Timezone-aware timestamp when execution occurred"
    )
    symbol: str = Field(min_length=1, description="Market ticker symbol")
    side: OrderSide = Field(description="Executed order side (BUY/SELL)")
    quantity: float = Field(gt=0, description="Filled quantity")
    fill_price: float = Field(gt=0, description="Execution price")
    fees: float = Field(
        default=0.0, ge=0, description="Execution and exchange fees incurred"
    )
    slippage: float = Field(
        default=0.0, description="Price slippage relative to expected price"
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timezone_aware(cls, v: datetime) -> datetime:
        """Ensure the timestamp is timezone-aware."""
        if v.tzinfo is None or v.tzinfo.utcoffset(v) is None:
            raise ValueError("Fill timestamp must be timezone-aware")
        return v
